// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxlyl1veXZE0oD1o7GEk-OGh8PPs6QjiY',
    appId: '1:633226661838:web:7d1b8ceb24cc5fd2bc659f',
    messagingSenderId: '633226661838',
    projectId: 'buzon-secreto-ecbe0',
    authDomain: 'buzon-secreto-ecbe0.firebaseapp.com',
    storageBucket: 'buzon-secreto-ecbe0.firebasestorage.app',
    measurementId: 'G-MNCPND3TTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQTpTW33LtxujEU7q3UWYWudnFG60vEbE',
    appId: '1:633226661838:android:ff4456704d499971bc659f',
    messagingSenderId: '633226661838',
    projectId: 'buzon-secreto-ecbe0',
    storageBucket: 'buzon-secreto-ecbe0.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-DuAcx--9D0lczmol06q9XeNLZh0Bgvc',
    appId: '1:633226661838:ios:53f2357958691eb0bc659f',
    messagingSenderId: '633226661838',
    projectId: 'buzon-secreto-ecbe0',
    storageBucket: 'buzon-secreto-ecbe0.firebasestorage.app',
    iosBundleId: 'com.example.buzonSecreto',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-DuAcx--9D0lczmol06q9XeNLZh0Bgvc',
    appId: '1:633226661838:ios:53f2357958691eb0bc659f',
    messagingSenderId: '633226661838',
    projectId: 'buzon-secreto-ecbe0',
    storageBucket: 'buzon-secreto-ecbe0.firebasestorage.app',
    iosBundleId: 'com.example.buzonSecreto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxlyl1veXZE0oD1o7GEk-OGh8PPs6QjiY',
    appId: '1:633226661838:web:95be1eb4f59cbeadbc659f',
    messagingSenderId: '633226661838',
    projectId: 'buzon-secreto-ecbe0',
    authDomain: 'buzon-secreto-ecbe0.firebaseapp.com',
    storageBucket: 'buzon-secreto-ecbe0.firebasestorage.app',
    measurementId: 'G-1ZE7R3EMD2',
  );
}
