// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg15RwE8zuztX_rD1NbqLCplSZXBDai8M',
    appId: '1:772574315599:web:84c890e873406f6ed0d63a',
    messagingSenderId: '772574315599',
    projectId: 'buzon-1cce8',
    authDomain: 'buzon-1cce8.firebaseapp.com',
    storageBucket: 'buzon-1cce8.firebasestorage.app',
    measurementId: 'G-DJ8QLR3N5M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXXVnN4zIMWioWRaoE48dlMKjfb3OM1Vc',
    appId: '1:772574315599:android:76d616d8394fb728d0d63a',
    messagingSenderId: '772574315599',
    projectId: 'buzon-1cce8',
    storageBucket: 'buzon-1cce8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB90JTescGATsaIa38oWH-SraARdcUdgUg',
    appId: '1:772574315599:ios:f164b7fda9243ed5d0d63a',
    messagingSenderId: '772574315599',
    projectId: 'buzon-1cce8',
    storageBucket: 'buzon-1cce8.firebasestorage.app',
    iosBundleId: 'com.example.buzonSecreto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB90JTescGATsaIa38oWH-SraARdcUdgUg',
    appId: '1:772574315599:ios:f164b7fda9243ed5d0d63a',
    messagingSenderId: '772574315599',
    projectId: 'buzon-1cce8',
    storageBucket: 'buzon-1cce8.firebasestorage.app',
    iosBundleId: 'com.example.buzonSecreto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg15RwE8zuztX_rD1NbqLCplSZXBDai8M',
    appId: '1:772574315599:web:96273a858f0d7048d0d63a',
    messagingSenderId: '772574315599',
    projectId: 'buzon-1cce8',
    authDomain: 'buzon-1cce8.firebaseapp.com',
    storageBucket: 'buzon-1cce8.firebasestorage.app',
    measurementId: 'G-M9EWJGEQ8Z',
  );
}
